packaging_format = 2
id = "mtg"
name = "mtg"
description.en = "Highly-opinionated MTPROTO proxy for Telegram"
version = "2.2.4~ynh1"
maintainers = ["YourName"]

[upstream]
license = "MIT"
code = "https://github.com/9seconds/mtg"
admindoc = "https://github.com/9seconds/mtg/blob/master/README.md"


[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
ram.build = "50M"
ram.runtime = "50M"
disk = "50M"

[install]
    [install.port]
    type = "string"
    ask.en = "Choose a port for the proxy to bind to"
    default = "3128"

    [install.secret]
    type = "string"
    ask.en = "Enter the MTProto Secret (Starts with 'ee...' or provide a fronting domain like google.com to auto-generate)"
    default = "google.com"

    [install.dns]
    type = "string"
    ask.en = "Enter the DNS resolver IP"
    default = "1.1.1.1"

    [install.prometheus]
    type = "boolean"
    ask.en = "Enable Prometheus metrics?"
    default = false

[resources]
    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/__APP__"
    owner = "__APP__:rwx"
    group = "__APP__:rx"

    [resources.ports]
    main.default = 3128
    main.exposed = "TCP"

    [resources.apt]
    packages = "curl, jq, tar, ca-certificates"
