#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    args.port = "3128"
    args.secret = "google.com"
    args.dns = "1.1.1.1"
    args.prometheus = false

    exclude = ["install.root", "install.subdir", "install.multi", "install.multi", "change_url"]
