#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================
source /usr/share/yunohost/helpers

#=================================================
# BACKUP
#=================================================
ynh_print_info "Declaring files to be backed up..."

ynh_backup "$install_dir"
