#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================

source /usr/share/yunohost/helpers

conf_dir=$install_dir/conf

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing systemd service..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_systemctl --action=stop --ignore_exceptions
ynh_systemctl --action=disable --ignore_exceptions

ynh_config_remove_systemd

#=================================================
# REMOVE CONFIGURATION FILES
# Note: system user, install_dir, apt packages, and firewall ports
# are automatically removed by YunoHost via [resources]
#=================================================
ynh_script_progression "Removing configuration files..."

ynh_safe_rm "$conf_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
