#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_config_add_systemd

yunohost service add "$app" \
    --description "MTProto proxy for Telegram" \
    --needs_exposed_ports "$port" \
    --log="/var/log/$app/mtg.log" 

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading $app's service..."

ynh_systemctl --action=enable
ynh_systemctl --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
