#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================
source /usr/share/yunohost/helpers

conf_dir=/etc/$YNH_APP_ID

#=================================================
# RESTORE
#=================================================
ynh_script_progression "Restoring configuration files..."

ynh_restore "$install_dir"
ynh_restore "$conf_dir"

#=================================================
# SYSTEMD + SERVICE REGISTRATION
#=================================================
ynh_script_progression "Restoring systemd service..."

ynh_config_add_systemd

yunohost service add "$app" \
    --description "MTProto proxy for Telegram" \
    --needs_exposed_ports "$port"

ynh_systemctl --action=enable
ynh_systemctl --action=start

ynh_script_progression "Restore complete!"
