#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================
source /usr/share/yunohost/helpers

conf_dir=$install_dir/conf

#=================================================
# STOP SERVICE
#=================================================
ynh_script_progression "Stopping mtg..."
ynh_systemctl --action=stop

#=================================================
# FETCH AND INSTALL LATEST MTG BINARY
#=================================================
ynh_script_progression "Downloading latest mtg binary..."

# $install_dir is set automatically from [resources.install_dir]
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="conf"  
chmod +x "$install_dir/mtg"
chown "$app:" "$install_dir/mtg"

#=================================================
# UPDATE CONFIGURATION
#=================================================
ynh_script_progression "Updating configuration..."

mtg_secret=$(ynh_app_setting_get --key=mtg_secret)
if [ -z "$mtg_secret" ] && [ -f "$conf_dir/mtg.toml" ]; then
    mtg_secret=$(grep "^secret =" "$conf_dir/mtg.toml" | cut -d '"' -f 2)
    [ -n "$mtg_secret" ] && ynh_app_setting_set --key=mtg_secret --value="$mtg_secret"
fi
[ "$prometheus" = "1" ] && prom_enabled="true" || prom_enabled="false"

ynh_config_add --template="mtg.toml" --destination="$conf_dir/mtg.toml"

# Ensure log directory exists
mkdir -p /var/log/$app
chown $app: /var/log/$app

#=================================================
# UPDATE SYSTEMD CONFIG
#=================================================
ynh_config_add_systemd

yunohost service add "$app" \
    --description "MTProto proxy for Telegram" \
    --needs_exposed_ports "$port" \
    --log="/var/log/$app/mtg.log" 


#=================================================
# START SERVICE
#=================================================
ynh_script_progression "Starting mtg..."
ynh_systemctl --action=start

ynh_script_progression "Upgrade complete!"
